project:
  type: website
  output-dir: docs
website:
  title: "Thiago Grezzi"
  navbar:
    left:
      - href: index.qmd
        text: Inicío
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



